name: "release extension"
description: "Generate a release for a precompiled gh extension"
inputs:
  gpg_fingerprint:
    description: "gpg fingerprint to use for signing releases. signing is disabled if empty."
  build_script_override:
    description: "use a custom build script instead of relying on built-in go compilation. see README.md for requirements."
  go_version:
    description: "The Go version to download (if necessary) and use. Supports semver spec and ranges."
    default: '1.16'
  go_stable: 
    description: "Whether to download only stable versions"
    default: 'true'
branding:
  color: purple
  icon: box
runs:
  using: composite
  steps:
    # TODO i hate setting this up even for people not using the default Go
    # build script, but there's no way to conditionalize it that I can figure
    # out.
    - uses: actions/setup-go@v2
      with:
        stable: ${{ inputs.go_stable }}
        go-version: ${{ inputs.go_version }}
    - run: ${{ github.action_path }}/build_and_release.sh
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        GH_EXT_BUILD_SCRIPT: ${{ inputs.build_script_override }}
        GH_EXT_PLATFORMS: ${{ inputs.platforms }}
        GPG_FINGERPRINT: ${{ inputs.gpg_fingerprint }}
      shell: bash
