name: "release extension"
description: "Generate a release for a precompiled gh extension"
inputs:
  gpg_fingerprint:
    description: "GPG fingerprint to use for signing releases"
  build_script_override:
    description: "Path to custom build script for producing binaries to upload"
  go_version:
    description: "The Go version to use for compiling (supports semver spec and ranges)"
    default: "1.18"
branding:
  color: purple
  icon: box
runs:
  using: composite
  steps:
    # TODO: figure out how to avoid setting up Go for non-Go extensions
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - run: ${{ github.action_path }}/build_and_release.sh
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        GH_EXT_BUILD_SCRIPT: ${{ inputs.build_script_override }}
        GPG_FINGERPRINT: ${{ inputs.gpg_fingerprint }}
      shell: bash
